### ISSUE TITLE
stupid ass mfing question

### ISSUE THREAD

**Issue by SapphireCodenz** [dex-interwebz/supremacy#1]
this works with the latest ver of the game or the 2018 build?

**Comment by silentcontribution** [comment]
Its for 2018 brainlet. You can probably update offsets and shit but it probably also needs to be updated for Panorama. Anyway, most features won't work probably.

**Comment by SapphireCodenz** [comment]
> Its for 2018 brainlet. You can probably update offsets and shit but it probably also needs to be updated for Panorama. Anyway, most features won't work probably.

r/claptrapisgay

**Comment by ntrzr** [comment]
shut up donkey fucker
